[character]
success_symbol = "[❯](bold {C_GREEN})"
error_symbol = "[❯](bold {C_RED})"

[cmd_duration]
format = "[took $duration](#{C_WHITE_DARKER}) "

[directory]
read_only = " "
style = "#{C_CYAN} bold"

[git_branch]
format = "[on](#{C_WHITE_DARKER}) [ $branch](#{C_MAGENTA}) "

[package]
style = ""
format = "[is](#{C_WHITE_DARKER}) [$version](#{C_WHITE}) "

[nodejs]
format = "[<node $version>](#{C_YELLOW}) "
