[character]
success_symbol = "[❯](bold {GREEN.hex})"
error_symbol = "[❯](bold {RED.hex})"

[cmd_duration]
format = "[took $duration](#{WHITE_DARKER.hex}) "

[directory]
read_only = " "
style = "#{CYAN.hex} bold"

[git_branch]
format = "[on](#{WHITE_DARKER.hex}) [ $branch](#{MAGENTA.hex}) "

[package]
style = ""
format = "[is](#{WHITE_DARKER.hex}) [$version](#{WHITE.hex}) "

[nodejs]
format = "[<node $version>](#{YELLOW.hex}) "
